Added unit tests for Taxes store
franciscobmacedo/remotefreelancept pull request #26
Opened 2024-01-10 16:26 UTC by luisrondow

This PR implements:
- tests for Pinia store: Taxes store
- an `.editorconfig` to enforce tabsize 🚀 
- removing `setupFiles` in vitest config (ain't necessary yet)

2024-01-11 11:51 UTC, franciscobmacedo commented
Can you also add this to github actions? 

You can rename the [github action's file](https://github.com/franciscobmacedo/remotefreelancept/blob/main/.github/workflows/build.yml)  to `workflow.yml` and have 2 jobs there: test and deploy. Just be sure to only deploy the app after the tests pass:

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds

2024-01-11 11:53 UTC, franciscobmacedo requested changes
Can you also add this to github actions? 

You can rename the [github action's file](https://github.com/franciscobmacedo/remotefreelancept/blob/main/.github/workflows/build.yml)  to `workflow.yml` and have 2 jobs there: test and deploy. Just be sure to only deploy the app after the tests pass:

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds

2024-01-16 12:10 UTC, luisrondow commented
Hey @franciscobmacedo!

Done! Can you review it again?

2024-01-16 13:14 UTC, franciscobmacedo approved these changes

2024-01-16 13:14 UTC, franciscobmacedo commented
perfect, thank you!!

2024-01-16 13:14 UTC, merged